[package]
name = "logistic-regression"
version.workspace = true
edition.workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
rand = { workspace = true }
linfa = { workspace = true }
linfa-logistic = { workspace = true }
anyhow = { workspace = true }
