[package]
name = "decision-trees"
version.workspace = true
edition.workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
rand = { workspace = true }
linfa = { workspace = true }
linfa-trees = { workspace = true }
anyhow = { workspace = true }
