[package]
name = "cnn"
version.workspace = true
edition.workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
