[package]
name = "k-means-clustering"
version.workspace = true
edition.workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
rand = { workspace = true }
linfa = { workspace = true }
linfa-clustering = { workspace = true }
anyhow = { workspace = true }
