[package]
name = "svm"
version.workspace = true
edition.workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
rand = { workspace = true }
linfa = { workspace = true }
linfa-svm = { workspace = true }
anyhow = { workspace = true }
