[package]
name = "gnn"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "gnn"
path = "src/main.rs"

[dependencies]
ndarray = { workspace = true }
